@hostname = https://api.rutsukun.pl

### check auth session
GET {{hostname}}/v1/auth/session HTTP/1.1
Content-Type: application/json

### fetch browser sessions
GET {{hostname}}/v1/auth/sessions HTTP/1.1
Content-Type: application/json

### auth switch browser session
POST https://api.rutsukun.pl/v1/auth/sessions HTTP/1.1
Content-Type: application/json

{
    "uuid": "260abc06-ac73-11ec-b069-525400889930"
}


### check auth session details
GET {{hostname}}/v1/auth/session/details HTTP/1.1
Content-Type: application/json

### end auth session
POST {{hostname}}/v1/auth/session/end HTTP/1.1
Content-Type: application/json

### check auth
POST https://api.rutsukun.pl/v1/auth HTTP/1.1
Content-Type: application/json

{
    "flow": "oauth"
}

### auth signin

POST https://api.rutsukun.pl/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "secret123"
}

