### get authn methods
GET https://api.rutsukun.pl/v1/me/authn HTTP/1.1
Content-Type: application/json

### setup authn otp
POST https://api.rutsukun.pl/v1/me/authn/otp/init-flow HTTP/1.1
Content-Type: application/json

### enable authn otp
PUT https://api.rutsukun.pl/v1/me/authn/otp/finish-flow HTTP/1.1
Content-Type: application/json

{
    "code": "239317"
}